Выполнена пагинация
Kirshach/junior-course-boilerplate pull request #4
Opened 2021-05-22 17:17 UTC by Kirshach

2021-05-23 09:29 UTC, kuflash requested changes
Есть некоторые места, которые нужно поправить

2021-05-23 09:29 UTC, kuflash commented on src/store/domain.js
> +export const productsSelector = (state) => slice(state).products;
Именование селекторов тоже лучше скорректировать. Это же все-таки функции для извлечения данных. И называть их лучше типа такого - `getProducts`. Обрати внимание на примеры в теоретической части. Скорректируй пожалуйста названия всех селекторов

2021-05-23 09:29 UTC, kuflash commented on src/store/app.js
> +const slice = (state) => state.app;
Очень абстрактное название для функции извлечения части стейта. Назови более контекстно, например `getAppState`. Поправь пожалуйста это во всех подобных файлах.

2021-05-23 09:29 UTC, kuflash commented on src/store/store.js
> +export const productsAndPagesSelector = createSelector(
Слишком общий селектор получается. Он возвращает данные, которые могут даже не потребоваться. Ведь для контейнера `ProductListContainer` нужен только результат из поля `products`, а для `PagesContainer` нужны поля `pagesCount` и `currentPage`. Такой селектор будет сложно переиспользовать в других местах, если это потребуется.

Лучше его разбить на несколько селекторов, которые будут возвращать только необходимую информацию. Т.е. у тебя могут получиться следующие селекторы:
- Получение отфильтрованного списка продуктов
- Получение данных для пагинации на основе отфильтрованного списка
- Получение данных для текущей страницы списка продуктов, на основе отфильтрованного списка и данных пагинации

2021-05-23 19:39 UTC, Kirshach commented on src/components/Pages/Pages.jsx
> +        <button
Я думаю, тут можно было бы подискутировать, по сути при нажатии на элемент пагинации происходит 
 скорее изменение содержимого одной и той же страницы - те же компоненты, тот же функционал, та же суть. Исторически это были разные страницы, конечно, но сейчас семантически, учитывая, что элемент истории в браузере уже давно существует как некоторая абстрактная сущность, не связанная с переходом на конкретную страницу и модифицируемая через кнопки ничем не отлично от ссылок... Я бы сказал, что на мой взгляд это скорее кнопка, чем ссылка. Энивей, исправлю

2021-05-23 19:41 UTC, Kirshach commented on src/components/Pages/Pages.jsx
> +        <button
Насчёт "открыть последнюю страницу в новой вкладке" - аргумент, согласен

2021-05-23 20:20 UTC, Kirshach commented on src/containers/AppContainer/AppContainer.jsx
> +class CategoryFieldsetContainer extends LogRender {
Косяк, естественно)

2021-05-23 20:36 UTC, Kirshach commented on src/store/store.js
> +export const productsAndPagesSelector = createSelector(
м, у меня чот выпадает из головы, что можно использовать derived селекторы для того, чтобы от них дерайвить другие селекторы

2021-05-24 07:00 UTC, kuflash requested changes
Есть еще недочеты в местах замены кнопки на ссылку.

2021-05-24 07:00 UTC, kuflash commented on src/components/Pagination/Pagination.jsx
> +          href="/"
А `href` почему ведет на корень? Это же ссылка "назад", т.е. она должна вести на предыдущую, с точки зрения пагинации, страницу. Т.е. если мы находимся на третьей странице, то ссылка должна вести на вторую.

2021-05-24 07:00 UTC, kuflash commented on src/components/Pagination/Pagination.jsx
> +                  href="/"
И тут тоже. Мы же таким образом теряем суть ссылки, которую можно открыть в новой вкладке. 

Я почему обратил на это внимание. У нас в html есть элементы, которые нужны для вполне конкретных ситуаций. И вот ссылки и кнопки это как раз такие элементы. Если действие пользователя, при клике на элемент перенаправляет его на другую страницу, то это точно ссылка. Да, с помощью SPA мы используем History API, для смены страницы, но тем не менее. Это все-же ссылка. И SPA в этом случае как бы является прогрессивным улучшением, которое позволяет перейти на страницу без полной её перезагрузки.

2021-05-24 07:04 UTC, kuflash commented on src/components/Pages/Pages.jsx
> +        <button
Насчет того, что пагинация меняет содержимое одной страницы - да. Но это лишь визуально :) Адрес страницы в адресной строке браузера меняется? Да. Query-параметры это такая же часть адреса, как и путь. Соответственно это явный переход на другую страницу. А для явных переходов на другую страницу у нас всегда используются ссылки.

2021-05-24 07:05 UTC, kuflash commented on src/store/store.js
> +export const productsAndPagesSelector = createSelector(
Это нормально :) С опытом будет работать на автоматизме.

2021-05-25 19:44 UTC, Kirshach commented on src/components/Pagination/Pagination.jsx
> +          href="/"
я думал, она до версии с роутером выполняет роль заглушки c хэндлером ;(

2021-05-25 19:48 UTC, Kirshach commented on src/components/Pagination/Pagination.jsx
> +          href="/"
типа... можно, конечно, реализовать один и тот же функционал через редакс + url, и если у нас **вдруг** отваливается js, то остаются ссылки, которые, правда, не понятно, как будут парситься, но... не знаю, мне показалось, что это довольно странно

2021-05-25 20:03 UTC, Kirshach commented on src/components/Pagination/Pagination.jsx
> +                  href="/"
ну, теперь согласен, справедливо

2021-05-26 06:42 UTC, kuflash commented on src/components/Pagination/Pagination.jsx
> +          href="/"
В курсе мы постепенно изучаем способы реализации. Если помнишь, мы сначала делали работу с состоянием, используя `Context`, а уже позже прикручивали `Redux`. Тут такой же принцип. Хоть и известно что далее будет добавление `Router`, но нам важно понять как он работает. А для этого полезно самому реализовать похожее поведение. Пусть ты и не вынес ссылки в отдельный компонент, но ты сделал доступную ссылку, которую можно скопировать или открыть в новой вкладке.

А если отваливается JS, то нам поможет серверный рендеринг, в этом случае ссылка останется ссылкой и пользователь будет работать с приложением, как с обычным сайтом, с полной перезагрузкой страницы при переходе по ссылкам. Но это уже тема отдельного урока :)

2021-05-26 06:44 UTC, kuflash commented
@Kirshach теперь вопросов нет :) Можешь вливать в `master`

2021-05-26 19:43 UTC, merged