Реализована корзина товаров
Kirshach/junior-course-boilerplate pull request #7
Opened 2021-06-12 23:31 UTC by Kirshach

2021-06-13 10:51 UTC, kuflash requested changes
Есть несколько моментов, которые нужно поправить

2021-06-13 10:51 UTC, kuflash commented on src/components/App/App.css
> +.page-main--not-found__title {
Странное именование класса. Ты используешь БЭМ именование или что-то другое? Если БЭМ, то тут есть ошибка. Класс блока не может быть одновременно элементом. Как я вижу этот селектор:
`блок--модификатор__элемент`. Какой кейс ты таким образом решаешь?

2021-06-13 10:51 UTC, kuflash commented on src/components/App/App.jsx
> +            <ProductNotFound productNotFound />
А пропс `productNotFound` нужен еще, если ты сделал отдельный компонент страницы "404" для кейса "Товар не найден"? Если нет, удали его пожалуйста

2021-06-13 10:51 UTC, kuflash commented on src/store/basket.js
> +    case ADD_PRODUCT_TO_BASKET:
После добавления/удаления товаров корзина уже не является сохраненной, поэтому, в этих кейсах нужно обновлять еще обновить состояние корзины.

2021-06-13 10:51 UTC, kuflash commented on src/components/Basket/Basket.jsx
> +          </div>
У меня почему-то не работает вот этот кейс. При возникновении ошибки этот текст не отображается, хотя в хранилище состояние корзины `FAILED`

![image](https://user-images.githubusercontent.com/815876/121804268-2aa67700-cc4e-11eb-89a9-027a52702133.png)

2021-06-13 10:51 UTC, kuflash commented on src/store/basket.js
> +      console.log(result);
Вывод в консоль лучше удалять :)

2021-06-14 18:52 UTC, Kirshach commented on src/components/App/App.css
> +.page-main--not-found__title {
подзабыл БЭМ

2021-06-16 07:41 UTC, kuflash commented
Теперь все хорошо. Вливай в `master`

2021-06-20 21:39 UTC, merged