Реализована страница корзины
Kirshach/junior-course-boilerplate pull request #8
Opened 2021-06-26 17:33 UTC by Kirshach

Я обленился / у меня не хватило фантазии для того, чтобы придумать способ перехода на страницу корзины, поэтому я неочевидно реализовал его через клик по заголовку "Корзина" в сайдбаре справа 😬

2021-06-27 10:24 UTC, kuflash requested changes
UX решение с кликабельным заголовком "Корзина" для перехода на страницу корзины хорошее :) Но есть недочеты в реализации

2021-06-27 10:24 UTC, kuflash commented on src/components/BasketSidebar/BasketSidebar.jsx
> +          </h2>
Вот эту часть лучше сделать ссылкой. Пользователь же может захотеть открыть корзину в новом окне. А в текущей реализации это будет невозможно.

2021-06-27 10:24 UTC, kuflash commented on src/components/BasketSidebar/BasketSidebar.jsx
> +    const isOnBasketPage = this.props.history.location.pathname === '/basket';
Лучше не привязывать такую логику к url. С течением жизни приложения url может меняться и нам придется всегда держать в голове что у нас есть код зависящий от актуального url корзины.

Тут есть 2 варианта:
- Выделить заголовок корзины в отдельный компонент, и где это необходимо, оборачивать его в ссылку. Соответственно сам компонент заголовка будет вне твоего компонента `BasketSidebar`
- Сделать флаг `isOnBasketPage` в виде пропса компонента и там где это необходимо пробрасывать его.

2021-06-27 10:24 UTC, kuflash commented on src/store/basket.js
> +          ...state.products, action.payload,
А почему ты решил изменить формат хранения данных в корзине? 

В новом варианте есть проблема - так как ты кладешь в состояние корзины всю структуру добавляемого продукта, то таким образом мы дублируем информацию о продукте в 2х местах - в списке всех продуктов и в списке добавленных в корзину товаров.

И если, допустим, нам понадобится как-то на лету обновлять информацию о товаре (например у нас в режиме live должна обновляться цена товара), то нам придется менять это в 2х местах нашего состояния.

А если бы в состоянии корзины у нах хранились только id добавленных товаров, то нам было бы достаточно написать селектор который бы получил список всех товаров и отфильтровал бы их по имеющимся id товаров из корзины. И вся информация о продукте лежит только в одном месте - у нас получается будет единый источник правды о наших продуктах.

2021-07-04 14:59 UTC, Kirshach commented on src/store/basket.js
> +          ...state.products, action.payload,
Потому что глупенький =)

2021-07-04 15:33 UTC, kuflash commented
@Kirshach получаю ошибки при переходе в корзину с добавленными товарами:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/815876/124390891-5f11ce00-dcf6-11eb-80c3-df2fdefd0d82.png">

2021-07-04 16:41 UTC, Kirshach commented
> @Kirshach получаю ошибки при переходе в корзину с добавленными товарами:
> <img alt="image" width="535" src="https://user-images.githubusercontent.com/815876/124390891-5f11ce00-dcf6-11eb-80c3-df2fdefd0d82.png">

🤦

2021-07-04 18:03 UTC, kuflash commented
@Kirshach все отлично :) Можешь вливать в `master`

2021-07-04 18:21 UTC, merged